name: Deploy Release
on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.5.0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm
      - name: Set up dependencies
        shell: bash
        run: |
          pnpm install
          pnpm ohm-generate
      - name: Build
        run: |
          for config in chrome firefox firefox-mv2; do
            pnpm webpack --config-name $config
            zip -rj dist/$config.zip dist/$config
          done
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.zip

  deploy-demo:
    name: Deploy Demo
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy-demo
        with:
          pulumi-access-token: ${{ secrets.PULUMI_ACCESS_TOKEN }}
