name: Deploy Release
on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: yarn
      - name: Set up dependencies
        run: |
          yarn install
          npm run ohm-generate
      - name: Build
        run: |
          for config in chrome firefox firefox-mv2; do
            npx webpack --config-name $config
            zip -rj dist/$config.zip dist/$config
          done
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.zip

  deploy-demo:
    name: Deploy Demo
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy-demo
