name: Deploy Release
on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: yarn
      - name: Set up dependencies
        run: |
          yarn install
          npm run ohm-generate
      - name: Build
        run: |
          for config in chrome firefox firefox-mv2; do
            npx webpack --config-name $config
            zip -rj dist/$config.zip dist/$config
          done
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.zip

  deploy-demo:
    name: Deploy Demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: yarn
      - name: Set up dependencies
        run: |
          yarn install
          npm run ohm-generate
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: poetry
      - uses: Gr1N/setup-poetry@v7
      - name: Set up Python Dependencies
        run: poetry install
      - name: Build Demo 
        run: |
          mkdir -p data/demo
          curl https://egghead.camfeenstra.com/demo.db -o data/demo/demo.db
          curl https://egghead.camfeenstra.com/demo-small.db -o data/demo/demo-small.db
          npx webpack --config-name demo
          make html
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::081142152120:role/egghead-github-role-2a57924
          aws-region: us-east-2
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
