name: run-tests
on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: yarn
      - name: Set up dependencies
        run: |
          yarn install
          npm run ohm-generate
      - run: npm run test
